name: starter_template
description: Flutter template project

version: 0.0.1+1

environment:
  sdk: ^3.9.2

dependencies:
  
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #default 
  intl: any
  meta: any

  #Utils
  logging: ^1.3.0
  async: ^2.13.0
  collection: ^1.19.1

  #Network
  http_middleware_client: ^1.0.0+2
  http: ^1.5.0

 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true